import { Metadata } from 'next'
import React from 'react'

type Props = {
  children: React.ReactNode
}

export const metadata: Metadata = {
  title: "Todo App | Sign Up",
  description: "Generated by create next app",
}

export default function layout({children}: Props) {
  return (
    <>{children}</>
  )
}